# This line will pull the node 12 image with debian stretch
FROM node:12-stretch

# CMD will execute the given command i.e with node immedietly log "Hello from Docker"
CMD [ "node", "-e" , "console.log(\"Hello from Docker\")"  ]